"""changed so many things: reactions and captions

Revision ID: cc64d732897a
Revises: e4338c095afb
Create Date: 2021-06-23 15:11:58.165415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc64d732897a'
down_revision = 'e4338c095afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_reactions', sa.Column('reaction', sa.Boolean(), nullable=True))
    op.drop_column('post_reactions', '_reaction')
    op.add_column('posts', sa.Column('caption', sa.String(length=255), nullable=True))
    op.drop_column('posts', '_caption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('_caption', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'caption')
    op.add_column('post_reactions', sa.Column('_reaction', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('post_reactions', 'reaction')
    # ### end Alembic commands ###
