"""empty message

Revision ID: 02f37635144e
Revises: e8d1f27e6a3a
Create Date: 2021-06-23 12:42:08.090501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f37635144e'
down_revision = 'e8d1f27e6a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_reactions', sa.Column('_reaction', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_reactions', '_reaction')
    # ### end Alembic commands ###
